### ISSUE TITLE
Use astropy.cosmology

### ISSUE THREAD

**Issue by kelle** [sambit-giri/AstronomyCalc#1]
Much of the functionality presented here is available in the [Astropy Cosmology sub-package](https://docs.astropy.org/en/stable/cosmology/index.html), which is very well tested and maintained.  This package will be more reliable and sustainable if it relied on `astropy.cosmology` rather than newly built functions.

Submitted as part of JOSE Review.
https://github.com/openjournals/jose-reviews/issues/261

**Comment by kelle** [comment]
See, for example, this tutorial: https://learn.astropy.org/tutorials/redshift-plot.html

**Comment by sambit-giri** [comment]
Thanks for these references. Though the cosmological calculations are similar to the `astropy.cosmology` package, this package is more focused on allowing students to get introduced to how the calculations are perform through the simple implementations. `astropy.cosmology` is better for research work where accuracy is very important.
