### ISSUE TITLE
Consider using the `emcee` package

### ISSUE THREAD

**Issue by kelle** [sambit-giri/AstronomyCalc#4]
Many of the functions in `mcmc.py` could be replaced by using the widely-used `emcee` package. 
https://emcee.readthedocs.io/en/stable/

Submitted as part of JOSE Review.
openjournals/jose-reviews#261

**Comment by sambit-giri** [comment]
The `mcmc.py` also contains a simple inference method, which is `Importance Sampling`, that is not suitable for real astronomical data but helps give the students an intuition of the posterior distribution.

**Comment by sambit-giri** [comment]
`emcee` is a very good package for MCMC but not suitable for teaching students what is happening under the hood. Of course, it is very good for them to be aware of such package that they can use later for better data analysis. I have extended the corresponding notebook mentioning several packages, such as `emcee`, `PolyChord` and `sbi`.
