### ISSUE TITLE
Contribute to Astropy Tutorials

### ISSUE THREAD

**Issue by kelle** [sambit-giri/AstronomyCalc#6]
Once the tutorials are updated to use Astropy, they would be a great addition to the Astropy tutorials!
https://learn.astropy.org/contributing/how-to-contribute

The Astropy Tutorials project has been in a bit of a lull the past couple of years but it has recently gotten a new lead and a new maintainer so we're optimistic to be publishing new notebooks very soon and these would be perfect!

Submitted as part of JOSE Review.
openjournals/jose-reviews#261

**Comment by sambit-giri** [comment]
Thank you for your thoughtful suggestion! I completely agree that integrating updated tutorials using Astropy into the Astropy Tutorials project would be a fantastic long-term contribution. I appreciate the information about the recent updates to the project and the link to the contribution guide.

**Comment by sambit-giri** [comment]
I will keep this strategy in mind to ensure my tutorials can become part of the Astropy Tutorials in the future. For now, since this suggestion does not directly impact the current structure or functionality of the package under review, I will close this issue.
